//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cathedral.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyXKickOff
    {
        public int Id { get; set; }
        public int PropertyId { get; set; }
        public int StatusId { get; set; }
        public Nullable<bool> ExtensionRequested { get; set; }
        public Nullable<bool> ExtensionApproved { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual Status Status { get; set; }
    }
}
